plugins:
  - jekyll-include-cache
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "contrast"
search: true
search_full_content: true
title: Your awesome title
email: your-email@domain.com
